package com.zengqi.ai.database.repository

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import java.security.SecureRandom

/**
 * Application-layer encryption for MemoryEntry content fields.
 *
 * SQLCipher encrypts the entire database file, but this adds an additional
 * defense-in-depth layer: memory entries remain encrypted even if the DB
 * file is extracted via backup or the SQLCipher key is compromised.
 *
 * Uses AES-256-GCM with a key stored in Android Keystore (hardware-backed
 * on devices with a TEE/StrongBox).
 *
 * Format: Base64(iv[12B] || ciphertext[var] || tag[16B])
 */
object MemoryCrypto {
    private const val KEYSTORE_ALIAS = "zengqi_memory_key"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_LENGTH = 128 // bits
    private const val GCM_IV_LENGTH = 12   // bytes
    // [M3 FIX] 加密前缀：encrypt 检测已有前缀则跳过，decrypt 检测无前缀则原样返回。
    // 消除双重加密风险（updateMemory 对已解密的 context 再 encrypt 会双重加密），
    // 以及对明文输入调用 decrypt 时的 ArrayIndexOutOfBoundsException。
    private const val PREFIX = "mem:v1:"

    private val key: SecretKey by lazy { getOrCreateKey() }

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }

        if (keyStore.containsAlias(KEYSTORE_ALIAS)) {
            val entry = keyStore.getEntry(KEYSTORE_ALIAS, null) as KeyStore.SecretKeyEntry
            return entry.secretKey
        }

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore"
        )
        keyGenerator.init(
            KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return keyGenerator.generateKey()
    }

    fun encrypt(plaintext: String): String {
        // [M3 FIX] 已加密则原样返回，防止双重加密
        if (plaintext.startsWith(PREFIX)) return plaintext
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv // auto-generated by GCM
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        // Format: PREFIX || IV (12B) || ciphertext+tag
        val combined = iv + ciphertext
        return PREFIX + android.util.Base64.encodeToString(combined, android.util.Base64.NO_WRAP)
    }

    fun decrypt(encoded: String): String {
        // [M3 FIX] 无前缀说明是明文（旧数据或未加密），原样返回
        if (!encoded.startsWith(PREFIX)) return encoded
        val payload = encoded.removePrefix(PREFIX)
        val combined = android.util.Base64.decode(payload, android.util.Base64.NO_WRAP)
        if (combined.size < GCM_IV_LENGTH) return encoded // 异常数据原样返回
        val iv = combined.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = combined.copyOfRange(GCM_IV_LENGTH, combined.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH, iv))
        val plaintext = cipher.doFinal(ciphertext)
        return String(plaintext, Charsets.UTF_8)
    }
}
